# Generated by Django 4.0.3 on 2022-04-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default=None, upload_to='file'),
        ),
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.ImageField(default=None, upload_to='img'),
        ),
        migrations.AddField(
            model_name='room',
            name='inoutwarranty',
            field=models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid'), ('Warranty with fee', 'Warranty with fee'), ('Waiting...', 'Waiting...')], default='Waiting...', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='role',
            field=models.IntegerField(choices=[(0, 'Recieved Mail'), (1, 'Inspection'), (2, 'Warranty clasification'), (3, 'Repairing'), (4, 'Testing'), (5, 'Delivering'), (6, 'CLOSED')], default=0),
        ),
    ]
