# Generated by Django 4.0.3 on 2022-04-20 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bms_message_file_message_images_room_inoutwarranty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
