# Generated by Django 4.0.3 on 2022-04-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_bms_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms',
            name='Amp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bms',
            name='SOC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bms',
            name='Vol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
